import { ReactNode } from "react"
import { hasLocale, NextIntlClientProvider } from "next-intl"
import type { Metadata, Viewport } from "next"
import "./globals.css"
import { Inter } from "next/font/google"
import { routing } from "@/i18n/routing"
import { notFound } from "next/navigation"
import { setRequestLocale } from "next-intl/server"
import Header from "@/components/Header"

export const viewport: Viewport = {
   themeColor: [
      { color: "#f4f4f5", media: "(prefers-color-scheme: light)" },
      { color: "#111111", media: "(prefers-color-scheme: dark)" },
   ],
   initialScale: 1,
   maximumScale: 5,
}

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

const inter = Inter({
   subsets: ["latin"],
})

export function generateStaticParams() {
   return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
   children,
   params,
}: Readonly<{
   children: ReactNode
   params: Promise<{ locale: string }>
}>) {
   const { locale } = await params
   if (!hasLocale(routing.locales, locale)) {
      notFound()
   }

   // Enable static rendering
   setRequestLocale(locale)

   return (
      <html
         lang={locale}
         className={`${inter.className} light scrollbar-hidden`}
         data-theme="light"
      >
         <body className="bg-background text-foreground flex min-h-screen flex-col antialiased">
            <NextIntlClientProvider>
               <Header />
               {children}
            </NextIntlClientProvider>
         </body>
      </html>
   )
}
